// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.Prism.Tests")]
[assembly: AssemblyProduct("Plainion.Prism")]
[assembly: AssemblyDescription("Plainion.Prism")]
[assembly: AssemblyCopyright("Copyright @ 2019")]
[assembly: AssemblyVersion("5.0.0")]
[assembly: AssemblyFileVersion("5.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Prism.Tests";
        internal const System.String AssemblyProduct = "Plainion.Prism";
        internal const System.String AssemblyDescription = "Plainion.Prism";
        internal const System.String AssemblyCopyright = "Copyright @ 2019";
        internal const System.String AssemblyVersion = "5.0.0";
        internal const System.String AssemblyFileVersion = "5.0.0";
    }
}
