// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.RI")]
[assembly: AssemblyProduct("Plainion.Prism")]
[assembly: AssemblyDescription("Plainion.Prism")]
[assembly: AssemblyCopyright("Copyright @ 2022")]
[assembly: AssemblyVersion("8.0.0")]
[assembly: AssemblyFileVersion("8.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.RI";
        internal const System.String AssemblyProduct = "Plainion.Prism";
        internal const System.String AssemblyDescription = "Plainion.Prism";
        internal const System.String AssemblyCopyright = "Copyright @ 2022";
        internal const System.String AssemblyVersion = "8.0.0";
        internal const System.String AssemblyFileVersion = "8.0.0";
    }
}
