// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.RI")]
[assembly: AssemblyProductAttribute("Plainion.Prism")]
[assembly: AssemblyDescriptionAttribute("Plainion.Prism")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2019")]
[assembly: AssemblyVersionAttribute("4.1.0")]
[assembly: AssemblyFileVersionAttribute("4.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.RI";
        internal const System.String AssemblyProduct = "Plainion.Prism";
        internal const System.String AssemblyDescription = "Plainion.Prism";
        internal const System.String AssemblyCopyright = "Copyright @ 2019";
        internal const System.String AssemblyVersion = "4.1.0";
        internal const System.String AssemblyFileVersion = "4.1.0";
    }
}
